-- =============================================================================
-- Bosh banner fonining rasmlari.
--
-- Banner shu paytgacha faqat ko'k gradient edi. Endi administrator uning
-- orqa foniga bitta rasm yoki bir nechta rasmdan albom yuklaydi: bitta
-- bo'lsa u doim turadi, bir nechta bo'lsa navbat bilan almashadi. Rasm
-- yo'q bo'lsa banner ilgarigidek gradientda qoladi.
--
-- Fayllar ochiq zonada (yangilik rasmlari kabi) va /api/v1/media/ orqali beriladi.
-- =============================================================================

create table home_banner_images (
    id bigint generated by default as identity,
    stored_name varchar(120) not null,
    original_name varchar(255) not null,
    display_order integer not null,
    created_at timestamp(6) with time zone not null,
    primary key (id),
    constraint uq_home_banner_images_stored_name unique (stored_name)
);
