-- =============================================================================
-- Boshlang'ich sxema (baseline).
--
-- Bu fayl entity modelidan bir marta hosil qilingan va ilovaning birinchi
-- versiyasidagi jadvallarni yaratadi. Undan keyingi har bir o'zgarish
-- alohida migratsiya fayli bo'lib qo'shiladi: V2__..., V3__... - shunda
-- bazaning holati kod bilan birga versiyalanadi va serverda "qo'lda"
-- o'zgartirish talab qilinmaydi.
--
-- MUHIM: chop etilgan migratsiyani tahrirlash mumkin emas - Flyway uning
-- nazorat yig'indisini saqlaydi va o'zgargani darrov xatolik beradi.
-- Xatoni tuzatish uchun yangi migratsiya yoziladi.
-- =============================================================================

create table about_section (
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone not null,
        tasks_title varchar(250),
        title varchar(250),
        body text,
        goal text,
        primary key (id)
    );

    create table about_tasks (
        display_order integer not null check ((display_order>=0)),
        about_id bigint not null,
        text varchar(500) not null,
        primary key (display_order, about_id)
    );

    create table attachments (
        complaint_id bigint not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        size_bytes bigint not null,
        content_type varchar(120) not null,
        stored_name varchar(120) not null unique,
        original_name varchar(255) not null,
        primary key (id)
    );

    create table complaint_status_history (
        changed_at timestamp(6) with time zone not null,
        changed_by_id bigint,
        complaint_id bigint not null,
        id bigint generated by default as identity,
        new_status varchar(20) not null check ((new_status in ('NEW','IN_REVIEW','NEED_INFO','RESOLVED','REJECTED'))),
        old_status varchar(20) check ((old_status in ('NEW','IN_REVIEW','NEED_INFO','RESOLVED','REJECTED'))),
        note text,
        primary key (id)
    );

    create table complaints (
        anonymous boolean not null,
        course_year integer,
        hidden_from_register boolean not null,
        incident_date date,
        assignee_id bigint,
        author_id bigint,
        closed_at timestamp(6) with time zone,
        created_at timestamp(6) with time zone not null,
        department_id bigint,
        faculty_id bigint,
        id bigint generated by default as identity,
        resolution_minutes bigint,
        updated_at timestamp(6) with time zone not null,
        locale varchar(10),
        status varchar(20) not null check ((status in ('NEW','IN_REVIEW','NEED_INFO','RESOLVED','REJECTED'))),
        study_form varchar(20) check ((study_form in ('FULL_TIME','EVENING','PART_TIME','DISTANCE','JOINT'))),
        tracking_code varchar(20) not null,
        reporter_phone varchar(30),
        reporter_type varchar(30) not null check ((reporter_type in ('STUDENT','MASTER_STUDENT','TEACHER','STAFF','PARENT','ALUMNI','EXTERNAL'))),
        accused_position varchar(40) check ((accused_position in ('TEACHER','HEAD_OF_DEPARTMENT','DEAN','VICE_DEAN','RECTORATE','ADMISSION_COMMITTEE','DORMITORY_STAFF','ACCOUNTING','REGISTRAR','SECURITY','OTHER_STAFF','UNKNOWN'))),
        category varchar(40) not null check ((category in ('EXAM_BRIBERY','GRADE_SELLING','RETAKE_PAYMENT','ATTENDANCE_PAYMENT','ACADEMIC_FRAUD','THESIS_FRAUD','ADMISSION_FRAUD','TRANSFER_FRAUD','SCHOLARSHIP_FRAUD','CONTRACT_PAYMENT_FRAUD','DORMITORY_CORRUPTION','FORCED_COLLECTION','PROCUREMENT_FRAUD','HIRING_NEPOTISM','ABUSE_OF_POWER','PROPERTY_MISUSE','OTHER'))),
        group_name varchar(50),
        reporter_name varchar(150),
        reporter_email varchar(180),
        subject_name varchar(200),
        title varchar(200) not null,
        incident_place varchar(250),
        description text not null,
        official_response text,
        primary key (id),
        constraint idx_complaints_tracking_code unique (tracking_code)
    );

    create table departments (
        active boolean not null,
        created_at timestamp(6) with time zone not null,
        faculty_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone not null,
        code varchar(20) not null,
        name varchar(200) not null,
        primary key (id),
        constraint uq_departments_faculty_code unique (faculty_id, code)
    );

    create table faculties (
        active boolean not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone not null,
        code varchar(20) not null,
        name varchar(200) not null,
        primary key (id),
        constraint idx_faculties_code unique (code)
    );

    create table news (
        published boolean not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        published_at timestamp(6) with time zone,
        updated_at timestamp(6) with time zone not null,
        view_count bigint not null,
        cover_image varchar(120),
        slug varchar(140) not null,
        title varchar(250) not null,
        summary varchar(500),
        body text not null,
        primary key (id),
        constraint idx_news_slug unique (slug)
    );

    create table news_block_images (
        display_order integer not null,
        block_id bigint not null,
        id bigint generated by default as identity,
        stored_name varchar(120) not null,
        caption varchar(300),
        original_name varchar(255),
        primary key (id)
    );

    create table news_blocks (
        display_order integer not null,
        id bigint generated by default as identity,
        news_id bigint not null,
        type varchar(10) not null check ((type in ('HEADING','TEXT','IMAGE','GALLERY'))),
        stored_name varchar(120),
        caption varchar(300),
        original_name varchar(255),
        text text,
        primary key (id)
    );

    create table news_images (
        display_order integer not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        news_id bigint not null,
        stored_name varchar(120) not null unique,
        caption varchar(300),
        original_name varchar(255) not null,
        primary key (id)
    );

    create table poll_options (
        correct boolean,
        display_order integer not null,
        id bigint generated by default as identity,
        question_id bigint,
        vote_count bigint not null,
        text varchar(250) not null,
        primary key (id)
    );

    create table poll_questions (
        display_order integer not null,
        multiple_choice boolean not null,
        required boolean not null,
        answered_count bigint not null,
        id bigint generated by default as identity,
        poll_id bigint not null,
        text varchar(300) not null,
        primary key (id)
    );

    create table poll_votes (
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        option_id bigint not null,
        poll_id bigint not null,
        question_id bigint,
        voter_key varchar(64) not null,
        primary key (id),
        constraint uq_poll_votes_option_voter unique (option_id, voter_key)
    );

    create table polls (
        active boolean not null,
        run_number integer,
        created_at timestamp(6) with time zone not null,
        ends_at timestamp(6) with time zone,
        id bigint generated by default as identity,
        previous_poll_id bigint,
        starts_at timestamp(6) with time zone,
        stopped_at timestamp(6) with time zone,
        updated_at timestamp(6) with time zone not null,
        voter_count bigint not null,
        type varchar(20) check ((type in ('SURVEY','QUIZ'))),
        title varchar(300),
        description varchar(1000),
        primary key (id)
    );

    create table staff_members (
        active boolean not null,
        display_order integer not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone not null,
        phone varchar(30),
        photo varchar(120),
        academic_degree varchar(150),
        full_name varchar(150) not null,
        reception_hours varchar(150),
        email varchar(180),
        position varchar(200) not null,
        biography text,
        primary key (id)
    );

    create table users (
        enabled boolean not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) with time zone not null,
        role varchar(20) not null check ((role in ('CITIZEN','MODERATOR','ADMIN'))),
        phone varchar(30),
        password_hash varchar(100) not null,
        full_name varchar(150) not null,
        email varchar(180) not null,
        primary key (id),
        constraint idx_users_email unique (email)
    );

    create index idx_attachments_complaint 
       on attachments (complaint_id);

    create index idx_history_complaint 
       on complaint_status_history (complaint_id);

    create index idx_complaints_status 
       on complaints (status);

    create index idx_complaints_category 
       on complaints (category);

    create index idx_complaints_faculty 
       on complaints (faculty_id);

    create index idx_complaints_created_at 
       on complaints (created_at);

    create index idx_news_published_at 
       on news (published_at);

    create index idx_news_block_images_block 
       on news_block_images (block_id);

    create index idx_news_blocks_news 
       on news_blocks (news_id);

    create index idx_news_images_news 
       on news_images (news_id);

    create index idx_poll_options_question 
       on poll_options (question_id);

    create index idx_poll_questions_poll 
       on poll_questions (poll_id);

    create index idx_poll_votes_question 
       on poll_votes (question_id);

    alter table if exists about_tasks 
       add constraint FK7dvjeji86h39hue9vpl1nae49 
       foreign key (about_id) 
       references about_section;

    alter table if exists attachments 
       add constraint FKs8jrkoxukg9d202qb7gv4hqou 
       foreign key (complaint_id) 
       references complaints;

    alter table if exists complaint_status_history 
       add constraint FKr4swqo5jqkg2drihvgg2yukst 
       foreign key (changed_by_id) 
       references users;

    alter table if exists complaint_status_history 
       add constraint FK3mbgevylfh21a5ngo39qwxvua 
       foreign key (complaint_id) 
       references complaints;

    alter table if exists complaints 
       add constraint FK7ewgs5fsbf0x2sqrxwlg3x6xj 
       foreign key (assignee_id) 
       references users;

    alter table if exists complaints 
       add constraint FKhr3lgf7is5it72t3a3myad08o 
       foreign key (author_id) 
       references users;

    alter table if exists complaints 
       add constraint FKrtes9yyruyvj69lxh3c9k05yf 
       foreign key (department_id) 
       references departments;

    alter table if exists complaints 
       add constraint FK8rks1rc96papeg0qi17nmuj27 
       foreign key (faculty_id) 
       references faculties;

    alter table if exists departments 
       add constraint FK6xpnvjcfa3l9gnqqb3x8v28iv 
       foreign key (faculty_id) 
       references faculties;

    alter table if exists news_block_images 
       add constraint FKq69lt5m37us29oaubevtu7sif 
       foreign key (block_id) 
       references news_blocks;

    alter table if exists news_blocks 
       add constraint FKndahq6ewe0ok7elsw5cvcp5au 
       foreign key (news_id) 
       references news;

    alter table if exists news_images 
       add constraint FKhcwu8kdkcw4mkqlygdq0g3dtq 
       foreign key (news_id) 
       references news;

    alter table if exists poll_options 
       add constraint FK1yv6qs5igdx6byep6csnx4mgx 
       foreign key (question_id) 
       references poll_questions;

    alter table if exists poll_questions 
       add constraint FKdiuqaq869156f0k67iwxvbysb 
       foreign key (poll_id) 
       references polls;

    alter table if exists poll_votes 
       add constraint FK974fgfa4183h12b8vns9226qs 
       foreign key (option_id) 
       references poll_options;

    alter table if exists poll_votes 
       add constraint FKmaogo469u92y072mev488em6p 
       foreign key (poll_id) 
       references polls;

    alter table if exists poll_votes 
       add constraint FKcsd2ifd85tbwssf900gmj6bri 
       foreign key (question_id) 
       references poll_questions;

    alter table if exists polls 
       add constraint FK2f2h84meqje94f2s8iepnvnq0 
       foreign key (previous_poll_id) 
       references polls;
