-- =============================================================================
-- Yangilash tokenlari (refresh token).
--
-- Kirish tokeni endi qisqa muddatli (15 daqiqa) va uni bekor qilib bo'lmaydi -
-- shuning uchun seans uzoq davom etishi uchun alohida, bazada saqlanadigan
-- yangilash tokeni kerak. Bazada tokenning o'zi emas, faqat SHA-256 xeshi
-- turadi: baza nusxasi qo'lga tushsa ham undan ishlaydigan token tiklab
-- bo'lmaydi.
-- =============================================================================

create table refresh_tokens (
    id bigint generated by default as identity,
    user_id bigint not null,
    token_hash varchar(64) not null,
    expires_at timestamp(6) with time zone not null,
    revoked_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone not null,
    primary key (id)
);

-- Xesh bo'yicha qidiruv har bir yangilashda bo'ladi va u yagona bo'lishi shart.
alter table refresh_tokens
    add constraint idx_refresh_tokens_hash unique (token_hash);

-- Foydalanuvchi o'chirilsa uning tokenlari ham qolmaydi.
alter table refresh_tokens
    add constraint fk_refresh_tokens_user
    foreign key (user_id) references users (id) on delete cascade;

-- "Bu foydalanuvchining barcha seanslarini uz" so'rovi uchun.
create index idx_refresh_tokens_user on refresh_tokens (user_id);
