-- =============================================================================
-- "Bo'lim haqida" sahifasi va xodimlar uchun tarjimalar.
--
-- Yangiliklardan farqli o'laroq bu ikkisi struktura sifatida bitta:
-- sarlavha, matn va ro'yxat har tilda ham shu tartibda qoladi, faqat matn
-- almashadi. Shuning uchun bu yerda alohida yozuv emas, tarjima jadvali.
--
-- Asosiy til (o'zbekcha) matni asosiy jadvallarda qoladi - shu tufayli
-- tarjima umuman qo'shilmasa ham sayt ilgarigidek ishlaydi. Tarjimada
-- bo'sh qolgan maydon asosiy matnga qaytadi.
-- =============================================================================

create table about_section_translations (
    id bigint generated by default as identity,
    about_id bigint not null,
    language varchar(10) not null,
    title varchar(250),
    body text,
    tasks_title varchar(250),
    goal text,
    primary key (id)
);

create table about_translation_tasks (
    translation_id bigint not null,
    display_order integer not null,
    text varchar(500) not null,
    primary key (translation_id, display_order)
);

create table staff_member_translations (
    id bigint generated by default as identity,
    member_id bigint not null,
    language varchar(10) not null,
    full_name varchar(150),
    position varchar(200),
    academic_degree varchar(150),
    biography text,
    reception_hours varchar(150),
    primary key (id)
);

-- Bir yozuvda bir tildan faqat bitta tarjima bo'ladi.
alter table about_section_translations
    add constraint idx_about_translation unique (about_id, language);

alter table staff_member_translations
    add constraint idx_staff_translation unique (member_id, language);

alter table about_section_translations
    add constraint about_translation_language_check
    check (language in ('UZ', 'UZ_CYRL', 'RU', 'EN'));

alter table staff_member_translations
    add constraint staff_translation_language_check
    check (language in ('UZ', 'UZ_CYRL', 'RU', 'EN'));

-- Asosiy yozuv o'chirilsa tarjimalari ham qolmaydi.
alter table about_section_translations
    add constraint fk_about_translation_about
    foreign key (about_id) references about_section (id) on delete cascade;

alter table about_translation_tasks
    add constraint fk_about_translation_tasks
    foreign key (translation_id) references about_section_translations (id) on delete cascade;

alter table staff_member_translations
    add constraint fk_staff_translation_member
    foreign key (member_id) references staff_members (id) on delete cascade;
