-- =============================================================================
-- So'rovnoma va test guruhlari.
--
-- Admin panelida so'rovnomalar bitta uzun ro'yxatda chiqardi. Ular yillar
-- davomida to'planadi (har semestrda yangi anketa, har mavzuda yangi test),
-- shuning uchun administrator ularni o'zi nomlagan guruhlarga ajratadi:
-- "2026 kuzgi anketalar", "Yangi xodimlar uchun testlar" kabi.
--
-- Guruh turi bilan bog'langan (SURVEY yoki QUIZ), chunki interfeysda
-- so'rovnomalar va testlar alohida sahifada. Umumiy guruh ikkala sahifada
-- ham yarmi bo'sh ko'rinardi.
--
-- Guruh MAJBURIY EMAS: guruhga biriktirilmagan so'rovnoma "Guruhsiz" bo'limida
-- qoladi va ilgarigidek ishlaydi. Shu tufayli mavjud yozuvlarga tegilmaydi.
-- =============================================================================

create table poll_groups (
    id bigint generated by default as identity,
    name varchar(200) not null,
    description varchar(500),
    type varchar(20) not null check ((type in ('SURVEY','QUIZ'))),
    display_order integer not null,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    primary key (id)
);

-- Bir turdagi ikkita guruh bir xil nom bilan yaratilmasin. Registr hisobga
-- olinmaydi: "2026 anketalar" va "2026 Anketalar" bir xil guruh.
create unique index idx_poll_groups_name
    on poll_groups (type, lower(name));

alter table polls
    add column group_id bigint;

-- Guruh o'chirilsa so'rovnomalar o'chmaydi, faqat guruhdan chiqadi:
-- guruh - tartibga solish vositasi, ma'lumot egasi emas.
alter table polls
    add constraint fk_polls_group
    foreign key (group_id) references poll_groups (id) on delete set null;

create index idx_polls_group on polls (group_id);
