-- =============================================================================
-- Testda savollarni tasodifiy tanlab berish.
--
-- Administrator test guruhini yaratayotganda har bir ishtirokchiga nechta
-- savol berilishini belgilaydi (masalan, 50 ta), guruhdagi testlarga esa katta
-- savollar bazasini kiritadi (200-300 ta). Har bir ishtirokchi o'z tasodifiy
-- to'plamini oladi va unda bitta savol ikki marta uchramaydi.
--
-- questions_per_attempt bo'sh bo'lsa ilgarigidek barcha savollar kiritilgan
-- tartibda beriladi - mavjud guruh va testlarga tegilmaydi.
-- =============================================================================

alter table poll_groups
    add column questions_per_attempt integer;

-- Ishtirokchiga qaysi savollar tushgani.
--
-- To'plam saqlanadi, har safar qaytadan tanlanmaydi: aks holda sahifani
-- yangilash yangi savollar berardi va ishtirokchi "osonroq" savollar
-- chiqquncha qayta-qayta yangilab turishi mumkin edi. Javoblar ham aynan shu
-- savollarga qarab tekshiriladi va baholanadi.
--
-- Savollar tashqi kalit bilan emas, ro'yxat sifatida saqlanadi: administrator
-- testni tahrirlab savolni o'chirsa, boshlangan to'plamlar uni shunchaki
-- tashlab ketadi.
--
-- token - testni boshlaganda ishtirokchiga beriladigan tasodifiy belgi. Anonim
-- ishtirokchi IP manzili bo'yicha taniladi va u uzun test davomida o'zgarishi
-- mumkin (mobil internet) - javob shu belgi bilan to'plamiga bog'lanadi.
create table poll_attempts (
    id bigint generated by default as identity,
    poll_id bigint not null,
    voter_key varchar(64) not null,
    token varchar(36) not null,
    question_ids text not null,
    question_count integer not null,
    created_at timestamp(6) with time zone not null,
    submitted_at timestamp(6) with time zone,
    primary key (id),
    -- Bir ishtirokchiga bitta testda bitta to'plam: ikkinchisi qayta tanlash
    -- imkonini berardi.
    constraint uq_poll_attempts_poll_voter unique (poll_id, voter_key),
    constraint uq_poll_attempts_token unique (token),
    constraint fk_poll_attempts_poll foreign key (poll_id) references polls (id)
);
