-- =============================================================================
-- Bosh sahifa matnlari admin panelidan tahrirlanadi.
--
-- Matnlar interfeysning tarjima fayllarida turardi va ularni faqat dasturchi
-- o'zgartira olardi. Endi administrator bosh bannerdagi sarlavha, matn,
-- tugmalar va "Qanday ishlaydi" bo'limini har bir til uchun o'zi yozadi.
--
-- Jadvalda faqat o'zgartirilgan matnlar turadi: yozuv bo'lmasa sayt
-- tarjima faylidagi asl matnni ko'rsatadi. Shu tufayli yangi tilda yoki
-- tahrirlanmagan maydonda sahifa hech qachon bo'sh qolmaydi.
-- =============================================================================

create table site_texts (
    id bigint generated by default as identity,
    text_key varchar(64) not null,
    language_code varchar(10) not null,
    text_value varchar(1000) not null,
    updated_at timestamp(6) with time zone not null,
    primary key (id),
    constraint uq_site_texts_key_language unique (text_key, language_code)
);
